import type { AnalysisResult } from './types';

// Illustrative dataset used for the ?property=slug deep link on /analyse,
// and for the demo rows/cards on Saved, History, Portfolio and Dashboard.
// Swap for the real Blackline API once every surface reads live data.
// Centralised here during the Next.js migration — previously this object
// (and slug-keyed variants of it) was duplicated across several HTML files.
export const PROPERTIES: Record<string, AnalysisResult> = {
  ashworth: {
    address: '14 Ashworth Rd, Manchester M20',
    price: 229950,
    beds: 3,
    type: 'terrace',
    sourceUrl: 'rightmove.co.uk/properties/154829201',
    verdict: 'strongbuy',
    verdictLabel: 'STRONG BUY',
    confidence: 94,
    scores: { growth: 82, valueAdd: 74, security: 87, cashflow: 91 },
    clauses: {
      cashflow: '6.4% net yield, well above the local BTL average',
      growth: 'sits in an active regeneration corridor, up 6.2% YoY',
      valueAdd: 'light cosmetic refresh (~£6,200) could lift rent ~£85/mo',
      security: 'six strong comparables and recent rental evidence',
    },
    financials: {
      purchase: 229950,
      stampDuty: 6898,
      deposit: 57488,
      mortgage: 847,
      rent: 1350,
      cashflow: 412,
      yieldPct: '6.4%',
      roiPct: '14.2%',
    },
    strategy: { btl: 82, brrr: 71, flip: 44 },
    comparables: [
      ['12 Ashworth Rd · 0.1mi', '£241,000'],
      ['7 Beech Road · 0.3mi', '£238,500'],
      ['21 Ashworth Rd · 0.2mi', '£245,000'],
    ],
    strengths: [
      'Priced ~8% below comparable sold prices',
      'Strong rental demand, 14-day average time-to-let',
      'Positive cashflow at 75% LTV',
    ],
    risks: ['Conservation area — planning restrictions apply', 'EPC rating D, may need upgrade by 2028'],
    summary:
      'Priced approximately 8% below three comparable sales within 0.4 miles, in an area with rental demand outpacing supply. Rental yield of 6.4% exceeds the local BTL average of 5.1%. Suggested offer range: £214,000–£221,000.',
  },
  corporation: {
    address: '9 Corporation St, Leeds LS1',
    price: 184000,
    beds: 2,
    type: 'apartment',
    sourceUrl: 'rightmove.co.uk/properties/148820113',
    verdict: 'buy',
    verdictLabel: 'BUY',
    confidence: 81,
    scores: { growth: 68, valueAdd: 60, security: 79, cashflow: 75 },
    clauses: {
      cashflow: '5.1% net yield against solid city-centre rental demand',
      growth: 'steady price growth, tracking the Leeds city average',
      valueAdd: 'modest — well-maintained, limited scope to add value',
      security: 'good liquidity, popular with young professional tenants',
    },
    financials: {
      purchase: 184000,
      stampDuty: 1840,
      deposit: 46000,
      mortgage: 679,
      rent: 980,
      cashflow: 301,
      yieldPct: '5.1%',
      roiPct: '9.8%',
    },
    strategy: { btl: 75, brrr: 52, flip: 30 },
    comparables: [
      ['14 Corporation St · 0.1mi', '£189,500'],
      ['2 Wellington Pl · 0.4mi', '£191,000'],
      ['22 Park Row · 0.3mi', '£178,250'],
    ],
    strengths: [
      'Strong tenant demand near the commercial core',
      'Low void periods reported for comparable units',
      'Established building, no known structural issues',
    ],
    risks: ['Service charge above area average', 'Limited upside without significant refurbishment'],
    summary:
      'A dependable city-centre buy-to-let with steady demand and low turnover. Growth is likely to track the wider Leeds market rather than outperform it — a solid income play rather than a value-add opportunity.',
  },
  riverside: {
    address: '3 Riverside Close, Bristol BS5',
    price: 312500,
    beds: 4,
    type: 'semi-detached',
    sourceUrl: 'rightmove.co.uk/properties/152003841',
    verdict: 'strongbuy',
    verdictLabel: 'STRONG BUY',
    confidence: 88,
    scores: { growth: 85, valueAdd: 80, security: 78, cashflow: 70 },
    clauses: {
      cashflow: '5.8% net yield with room to grow post-refurbishment',
      growth: 'one of Bristol’s fastest-appreciating postcodes',
      valueAdd: 'loft and side-return extension potential, subject to planning',
      security: 'active family-home market, low days-on-market',
    },
    financials: {
      purchase: 312500,
      stampDuty: 9375,
      deposit: 78125,
      mortgage: 1150,
      rent: 1800,
      cashflow: 650,
      yieldPct: '5.8%',
      roiPct: '12.1%',
    },
    strategy: { btl: 70, brrr: 65, flip: 83 },
    comparables: [
      ['9 Riverside Close · 0.1mi', '£324,000'],
      ['15 Mill Lane · 0.3mi', '£318,750'],
      ['4 Boat Yard Rd · 0.2mi', '£331,000'],
    ],
    strengths: [
      'Extension potential adds an estimated £38k margin on flip',
      'Strong family-home demand, low days-on-market',
      'Appreciation outpacing the wider Bristol market',
    ],
    risks: [
      'Refurbishment budget sensitive to build-cost inflation',
      'Planning consent not yet secured for extension',
    ],
    summary:
      'A well-located family home with genuine value-add potential through a side-return extension, subject to planning. Even without extending, the underlying growth and rental fundamentals support a strong buy.',
  },
  orchard: {
    address: '2 Orchard Lane, Liverpool L8',
    price: 142000,
    beds: 2,
    type: 'terrace',
    sourceUrl: 'rightmove.co.uk/properties/149773302',
    verdict: 'buy',
    verdictLabel: 'BUY',
    confidence: 79,
    scores: { growth: 66, valueAdd: 58, security: 74, cashflow: 80 },
    clauses: {
      cashflow: '5.9% net yield, comfortably cashflow positive',
      growth: 'steady, tracking inner-Liverpool regeneration',
      valueAdd: 'cosmetic updates only — kitchen and bathroom dated',
      security: 'reliable tenant demand, close to universities',
    },
    financials: {
      purchase: 142000,
      stampDuty: 1420,
      deposit: 35500,
      mortgage: 520,
      rent: 850,
      cashflow: 210,
      yieldPct: '5.9%',
      roiPct: '13.0%',
    },
    strategy: { btl: 79, brrr: 60, flip: 35 },
    comparables: [
      ['11 Orchard Lane · 0.1mi', '£146,500'],
      ['5 Ivy Street · 0.2mi', '£139,000'],
      ['18 Orchard Lane · 0.2mi', '£148,000'],
    ],
    strengths: [
      'Consistently strong student and young-professional demand',
      'Low purchase price supports a healthy net yield',
      'Straightforward, low-risk BTL candidate',
    ],
    risks: [
      'Kitchen and bathroom will need updating within 2–3 years',
      'Slower capital growth than city-centre comparables',
    ],
    summary:
      'A dependable, low-risk buy-to-let with a healthy net yield. Growth will likely be modest, but the entry price and cashflow profile make this a solid income-focused addition to a portfolio.',
  },
  kings: {
    address: '55 Kings Ave, Sheffield S2',
    price: 198750,
    beds: 3,
    type: 'terrace',
    sourceUrl: 'rightmove.co.uk/properties/151220098',
    verdict: 'invest',
    verdictLabel: 'INVESTIGATE FURTHER',
    confidence: 72,
    scores: { growth: 60, valueAdd: 55, security: 68, cashflow: 72 },
    clauses: {
      cashflow: '6.0% net yield, though rental evidence is thinner here',
      growth: 'in-line with the city average, no clear catalyst yet',
      valueAdd: 'some potential, condition report recommended',
      security: 'evidence base is moderate — worth a second look',
    },
    financials: {
      purchase: 198750,
      stampDuty: 1988,
      deposit: 49688,
      mortgage: 731,
      rent: 1100,
      cashflow: 301,
      yieldPct: '6.0%',
      roiPct: '11.4%',
    },
    strategy: { btl: 72, brrr: 68, flip: 40 },
    comparables: [
      ['48 Kings Ave · 0.2mi', '£203,000'],
      ['12 Abbey Rd · 0.4mi', '£195,500'],
      ['61 Kings Ave · 0.1mi', '£210,000'],
    ],
    strengths: ['Attractive headline yield versus purchase price', 'Reasonable transport links to the city centre'],
    risks: [
      'Only two directly comparable sales in the last 6 months',
      'No recent EPC on record — condition unverified',
      'Rental evidence relies on asking prices, not agreed lets',
    ],
    summary:
      'The headline numbers are attractive, but the evidence base is thinner than usual — fewer comparables and unverified rental figures. Worth a viewing and an EPC check before committing.',
  },
  milton: {
    address: '27 Milton Road, Nottingham NG7',
    price: 151000,
    beds: 2,
    type: 'terrace',
    sourceUrl: 'rightmove.co.uk/properties/147650221',
    verdict: 'caution',
    verdictLabel: 'PROCEED WITH CAUTION',
    confidence: 64,
    scores: { growth: 48, valueAdd: 40, security: 52, cashflow: 45 },
    clauses: {
      cashflow: 'thin — only marginally cashflow positive at current rent',
      growth: 'flat, no significant catalysts identified nearby',
      valueAdd: 'limited without a full refurbishment',
      security: 'below-average confidence, rents may be optimistic',
    },
    financials: {
      purchase: 151000,
      stampDuty: 1510,
      deposit: 37750,
      mortgage: 557,
      rent: 780,
      cashflow: 45,
      yieldPct: '4.8%',
      roiPct: '6.9%',
    },
    strategy: { btl: 58, brrr: 50, flip: 20 },
    comparables: [
      ['19 Milton Road · 0.1mi', '£149,000'],
      ['33 Milton Road · 0.2mi', '£153,500'],
      ['8 Elm Court · 0.3mi', '£146,000'],
    ],
    strengths: ['Low entry price relative to the wider Nottingham market'],
    risks: [
      'Rent appears to be priced above achievable market rate',
      'Net yield below the 5.5% threshold for this strategy',
      'Weak growth signals — no regeneration activity nearby',
    ],
    summary:
      'The numbers work on paper, but rental assumptions look optimistic against comparable lets nearby, and there’s little to suggest capital growth in the short term. Re-run this analysis with a verified rental valuation before proceeding.',
  },
  factory: {
    address: '18 Factory Lane, Bradford BD1',
    price: 96000,
    beds: 2,
    type: 'terrace',
    sourceUrl: 'rightmove.co.uk/properties/145981027',
    verdict: 'pass',
    verdictLabel: 'PASS',
    confidence: 58,
    scores: { growth: 30, valueAdd: 35, security: 40, cashflow: 38 },
    clauses: {
      cashflow: 'low net yield once realistic voids are factored in',
      growth: 'declining population trend in this specific postcode',
      valueAdd: 'would require substantial capital to bring to standard',
      security: 'weak evidence base, high vacancy risk',
    },
    financials: {
      purchase: 96000,
      stampDuty: 0,
      deposit: 24000,
      mortgage: 355,
      rent: 580,
      cashflow: 45,
      yieldPct: '3.6%',
      roiPct: '2.1%',
    },
    strategy: { btl: 35, brrr: 40, flip: 15 },
    comparables: [
      ['22 Factory Lane · 0.1mi', '£93,500'],
      ['6 Mill Street · 0.3mi', '£98,000'],
    ],
    strengths: ['Very low entry price'],
    risks: [
      'Net yield well below strategy threshold',
      'Only two weak comparables, low confidence in valuation',
      'Area showing signs of declining rental demand',
      'EPC and structural condition unverified',
    ],
    summary:
      'This does not meet Blackline’s minimum evidence or yield thresholds for the strategies analysed. The low purchase price does not offset weak growth signals and thin rental demand in this specific street.',
  },
};

export type DemoSlug = keyof typeof PROPERTIES;

export function findDemoSlugBySourceUrl(sourceUrl: string): DemoSlug | undefined {
  return (Object.keys(PROPERTIES) as DemoSlug[]).find((slug) => PROPERTIES[slug].sourceUrl === sourceUrl);
}
